# Generated by Django 2.2.27 on 2022-03-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('AccountID', models.AutoField(primary_key=True, serialize=False)),
                ('AccountPhoto', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=200)),
                ('ProjectDesc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('ProjectManagerID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('ProjectTypeID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('SkillID', models.AutoField(primary_key=True, serialize=False)),
                ('SkillAttributs', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SkillList',
            fields=[
                ('SkillListID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
