# Generated by Django 2.2.27 on 2022-03-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220320_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='SkillListID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='availabilitylist',
            name='AccountID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='availabilitylist',
            name='ProjectID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectManagerID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectTypeID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectinterest',
            name='AccountID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectinterest',
            name='ProjectID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='AccountID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projecttype',
            name='SkillListID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skilllist',
            name='SkillID',
            field=models.IntegerField(default=0),
        ),
    ]
