# Generated by Django 2.2.27 on 2022-03-22 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220321_1754'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailabilityList',
        ),
        migrations.DeleteModel(
            name='SkillList',
        ),
        migrations.RemoveField(
            model_name='account',
            name='SkillListID',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='SkillListID',
        ),
        migrations.AddField(
            model_name='account',
            name='SkillID',
            field=models.ManyToManyField(to='app.Skill'),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='SkillID',
            field=models.ManyToManyField(to='app.Skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ProjectTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ProjectType'),
        ),
        migrations.AlterField(
            model_name='projectinterest',
            name='AccountID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Account'),
        ),
        migrations.RemoveField(
            model_name='projectinterest',
            name='ProjectID',
        ),
        migrations.AddField(
            model_name='projectinterest',
            name='ProjectID',
            field=models.ManyToManyField(to='app.Project'),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='AccountID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Account'),
        ),
    ]
