# Generated by Django 2.2.27 on 2022-03-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220321_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='ProjectTypeName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
