# Generated by Django 2.2.27 on 2022-04-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_projecttype_projecttypename'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='SkillName',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
