# Generated by Django 2.2.27 on 2022-04-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_skill_skillname'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
