# Generated by Django 2.2.27 on 2022-04-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='AccountID',
            field=models.ManyToManyField(to='app.Account'),
        ),
        migrations.DeleteModel(
            name='ProjectInterest',
        ),
    ]
